shop = [{"name": "chicken", "price": 10, "description": "chicken men-men", "emoji": "🐓"},
        {"name": "parrot", "price": 20, "description": "birb machine", "emoji": "🦜"},
        {"name": "watch", "price": 50, "description": "Time", "emoji": "⌚️"},
        {"name": "horse", "price": 70, "description": "Juan", "emoji": "🐴"},
        {"name": "Sword", "price": 100, "description": "defence", "emoji": "⚔️"},
        {"name": "Rifle", "price": 500, "description": "shoot", "emoji": "<:rifle:927932095270101053>"},
        {"name": "Laptop", "price": 1000, "description": "let's work", "emoji": "💻️"},
        {"name": "tonk", "price": 3000, "description": "Defend your house", "emoji": "<:vn_tonk:927936254237114408>"},
        {"name": "Mac", "price": 5000, "description": "Luxury", "emoji": "🧑‍💻️"},
        {"name": "platinum", "price": 20000, "description": "Show of your status", "emoji": "💍️"},
        {"name": "silver", "price": 50000, "description": "cool kid", "emoji": "🥄"},
        {"name": "gold", "price": 200000, "description": "rich kid who like to show off", "emoji": "<:gold:927938720533999686>"},
        {"name": "diamonds", "price": 600000, "description": "extreme rich kid", "emoji": "💎"},
        {"name": "FireMiner", "price": 1542000, "description": "Mine FireCoin", "emoji": "<:stonk:888045236188762112>"}]
